#!/bin/sh

TMP_DIR=snapshot
HTML_DIR=collapseos

# grab latest snapshot
rm -rf "$TMP_DIR"
mkdir "$TMP_DIR"
releasedate=$(./grab-collapseos --dir snapshot)
curdate=$(date +"%Y-%m-%d %H:%M:%S")

# update footer template
cat > templates/foot.tt <<END
<p>This page generated at $curdate from documentation in CollapseOS snapshot <a href="https://collapseos.org/collapseos-$releasedate.tar.gz">$releasedate</a>.</p>
END

# create html
rm -rf "$HTML_DIR"
mkdir "$HTML_DIR"
./mk-html-doc -d "$TMP_DIR"/doc -o "$HTML_DIR" -t templates/

# clean up
rm -rf "$TMP_DIR"
